services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: variable-storage-object-comparison
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: variable-storage-object-comparison-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
