services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: file-uploads
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx:
    image: nginx:1.19-alpine
    container_name: file-uploads-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
